apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-ticker-visual-identity
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: ticker-visual-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_ticker_visual_identity
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_ticker_visual_identity
