include:
- ./func/*
kind: ArchiveUploadSpec
name: func-gip3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: ticker-visual-fn-bda5c8a0-b26f-4928-881f-6e4edc8aa19e
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-ticker-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-gip3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-03-04T21:59:59Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: ticker-visual-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-ticker-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_ticker_visual_identity
    packageref:
      name: ticker-visual-fn-bda5c8a0-b26f-4928-881f-6e4edc8aa19e
      namespace: default
  requestsPerPod: 1
  resources: {}
