apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 389504bb-f34a-4041-9d80-a0dcc0bd508d
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: ticker-visual-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_ticker
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_ticker
