apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 9e3466c4-7609-487d-a69d-6cabd53a4c16
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: ticker-visual-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get-ticker-visual-identity
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get-ticker-visual-identity
